name: Run awesome lint

on:
  push:
    # Run against main branch only.
    branches: [main]
  pull_request:
    # Include events emitted on code change only.
    types: [opened, synchronize]

jobs:
  awesome-lint-workflow:
    runs-on: ubuntu-latest
    name: Linting with awesome-lint
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use Node.js 10.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - run: npx awesome-lint
